/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thaint' at '7/29/16 2:34 PM' with Gradle 2.14
 *
 * @author thaint, @date 7/29/16 2:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
